# Generated by Django 4.1.2 on 2023-07-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cliente', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(max_length=30)),
                ('fono', models.CharField(max_length=12)),
                ('correo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id_cuadro', models.AutoField(db_column='idCuadro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('artista', models.CharField(max_length=80)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('anno_creacion', models.DateField()),
                ('imagen', models.ImageField(upload_to='cuadros')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
                ('total', models.IntegerField()),
                ('rut_cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_compra', models.AutoField(db_column='idCompra', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_cuadro', models.ForeignKey(db_column='id_cuadro', on_delete=django.db.models.deletion.CASCADE, to='tienda.cuadro')),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='tienda.pedido')),
                ('rut_cliente', models.ForeignKey(db_column='rut_cliente', on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente')),
            ],
        ),
    ]
