# Generated by Django 4.1.2 on 2023-07-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='rut_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='rut_cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
